// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/29/2026, 6:11:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/hiem/code-ubuntu/pro/template/templatepizza/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/plugins/**/*.{js,ts,mjs}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/composables/**/*.{js,ts,mjs}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/utils/**/*.{js,ts,mjs}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/hiem/code-ubuntu/pro/template/templatepizza/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;